name: Build Development Docker Images in CI

on:
  push:
    branches:
      - develop
      - 'feature/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_KEY }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ secrets.DOCKER_HUB_NS }}/k6-influx-dkr
          tags: |
            type=sha,event=branch,prefix={{branch}}-
            type=sha,event=pr,prefix={{branch}}-

      - name: Build and push Web Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
